# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Navidrome paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ navidrome_uid }}"
    group: "{{ navidrome_gid }}"
  with_items:
    - "{{ navidrome_base_path }}"
    - "{{ navidrome_data_path }}"

- name: Ensure Navidrome support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ navidrome_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ navidrome_uid }}"
    group: "{{ navidrome_gid }}"
  with_items:
    - env
    - labels

- name: Ensure Navidrome container image is pulled
  community.docker.docker_image:
    name: "{{ navidrome_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ navidrome_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else navidrome_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Navidrome container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ navidrome_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Navidrome systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/navidrome.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ navidrome_identifier }}.service"
    mode: "0644"
