# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Navidrome installation tasks
  block:
    - name: Validate Navidrome configuration
      when: navidrome_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Navidrome
      when: navidrome_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-navidrome
    - install-all
    - install-navidrome

- name: Perform Navidrome uninstallation tasks
  block:
    - name: Uninstall Navidrome
      when: not navidrome_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-navidrome
